require "spec_helper"

describe "Routing" do
  describe "Paths Generated by Custom Routes:" do
    it "has a path for searching within an item" do
      expect(:get => "/catalog/111/hits").to route_to(:controller => "catalog", :action => "hits", :id => "111")
    end
  end
end
